# We simply inherit the Python 3 image. This image does
# not particularly care what OS runs underneath
FROM python:3.9

RUN git clone https://github.com/matthieuDev/coproximity_create_vocabulary.git

WORKDIR coproximity_create_vocabulary
#RUN pip install --upgrade -r requirements.txt
RUN pip install -e . 
RUN python coproximity_create_vocabulary/test_requirements.py
